# Generated by Django 3.0 on 2021-02-25 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('tamaño', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='productos')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Rubro')),
            ],
        ),
    ]
